### ISSUE TITLE
请问vnc viewer怎么设置？ 老是连不上

### ISSUE THREAD

**Issue by twd-sky** [gotoeasy/docker-ubuntu-desktop#1]
RT  谢谢

**Comment by gotoeasy** [comment]
1、docker ps -a 查看服务是否正常启动了（服务器影响有时分辨率过大会启动失败）
2、有没有修改5900默认端口的映射，有修改的话连接字符串的地址后面要加上端口号
3、防火墙或安全策略之类是否放行了相应端口
4、客户端有没问题，我用VNC Viewer一直都很正常

**Comment by gotoeasy** [comment]
按步骤检查
