### ISSUE TITLE
mstsc how to connection the docker 

### ISSUE THREAD

**Issue by destinyclown** [gotoeasy/docker-ubuntu-desktop#10]
我想用window 自带的mstsc远程链接过去容器，请教一下可以怎么样做

**Comment by gotoeasy** [comment]
> 我想用window 自带的mstsc远程链接过去容器，请教一下可以怎么样做

![image](https://user-images.githubusercontent.com/9602197/227939349-4af5b308-7bb1-43f6-91d1-0a24a89403b4.png)
比如docker运行启动增加端口映射，然后进入容器执行命令开启

**Comment by gotoeasy** [comment]
> 我想用window 自带的mstsc远程链接过去容器，请教一下可以怎么样做

![image](https://user-images.githubusercontent.com/9602197/227939349-4af5b308-7bb1-43f6-91d1-0a24a89403b4.png)
比如docker运行启动增加端口映射，然后进入容器执行命令开启

**Comment by destinyclown** [comment]
我用docker run -d -p 22:22 -p 5900:5900 gotoeasy/ubuntu-desktop来启动的
然后开启xrdp
![企业微信截图_168025055413](https://user-images.githubusercontent.com/10192335/229064807-c4340a38-81f9-4ac2-87ef-03de5f9d199d.png)

**Comment by gotoeasy** [comment]
端口加上啊 -p 3389:3389
不然你连哪里去？

**Comment by destinyclown** [comment]
![企业微信截图_16802531387246](https://user-images.githubusercontent.com/10192335/229075491-42b4cc24-e201-4ff0-9c31-43ed21d63566.png)
还是不行大佬

**Comment by gotoeasy** [comment]
正如提示，原因也都已经给出了啊

【计算机无法连接到远程计算机上的另一个控制台会话，原因是你正在运行一个控制台会话。】
这话翻译过来的意思就是，你在自己控制自己，远程桌面不干

1种方式，是你本地设定调整网络之类，让远程桌面软件认为是在连接不同机器
另一种，你用真实的不同机器去做这样的事，正常的连接到其他服务器，也就会一切正常



基础的东西自己也要动动脑筋啊，别走一步问一步，这种习惯多不好
