### ISSUE TITLE
vnc-viewer直接复制汉字乱码

### ISSUE THREAD

**Issue by rplees** [gotoeasy/docker-ubuntu-desktop#12]
你好， 可以解决下vnc-viewer复制汉字到目标机，粘贴出来就是乱码， 可以支持下吗

**Comment by gotoeasy** [comment]
如果是用RealVNC 的 vnc-viewer ，那确实可能乱码，这个是第三方工具层面问题，镜像本身基本上解决不了。

建议使用tigervnc官网的vncviewer客户端
https://sourceforge.net/projects/tigervnc/files/stable/1.13.1/
