### ISSUE TITLE
ubuntu:20.04

### ISSUE THREAD

**Issue by leedchou** [gotoeasy/docker-ubuntu-desktop#14]
Hi,

感谢你的开源，我想用Ubuntu 20.04版本的系统，直接在dockefile里改`FROM ubuntu:20.04`，另外加了一句`echo 'service xrdp start' >> /root/startup.sh && \`。镜像能够制作成功，但是容器不能连接上，不知道是什么原因，我试过18.04是没问题的。

另外，好像dockerfile里有些命令会报错。

Best regards

**Comment by gotoeasy** [comment]
20.04没试过，也许是有差异，包括20.04时的dockerfile打包报错
暂时还没这个时间试验，得自己调查看了，如果成功，欢迎分享

**Comment by gotoeasy** [comment]
没有这个计划，因此关闭
