### ISSUE TITLE
有什么办法，可以删除这个提示：您使用的是不受支持的命令行标记: --no-sandbox。稳定性和安全性会有所下降。

### ISSUE THREAD

**Issue by luzihang123** [gotoeasy/docker-ubuntu-desktop#16]
![image](https://github.com/user-attachments/assets/3bbb22ee-d770-41ef-b617-9d6f6970c7bb)
您使用的是不受支持的命令行标记: --no-sandbox。稳定性和安全性会有所下降。

**Comment by gotoeasy** [comment]
每次打开后手动关闭提示，呵呵
docker环境的这个桌面系统有一定的阉割限制，设计目的不同，不能和常规桌面系统相比较

**Comment by luzihang123** [comment]
> 每次打开后手动关闭提示，呵呵 docker环境的这个桌面系统有一定的阉割限制，设计目的不同，不能和常规桌面系统相比较

我想了2个方案：
1、（相对不技术的方式）通过pyautogui，click对应的坐标。但是容器的分辨率会改，坐标也会变。坐标通过环境变量，可以控制。
2、参考 kasmweb/desktop的dockerfile，https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/chrome/install_chrome.sh

我发现他的chrome，通过 no-sandbox启动，但是没有这个提示。（kasmweb也有缺点，似乎没用--disable-dev-shm-usage启动，导致我在公司k8s跑，有些网页会crash。虚拟机、本地电脑没问题。）

**Comment by luzihang123** [comment]
## 参考 
https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/chrome/install_chrome.sh

## 解释如下：

从你提供的脚本内容来看，脚本中确实包含了一些用来隐藏或修改 Google Chrome 的警告和提示的设置。这里是一些主要的相关配置：

 1. Chrome 启动参数
脚本定义了 `CHROME_ARGS` 变量，其中包括几个参数，这些参数可能影响 Chrome 的警告和提示显示：

- `--no-sandbox`: 禁用沙箱，通常会触发安全警告。
- `--no-first-run`: 避免首次运行时显示欢迎页面。
- `--simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT'`: 模拟 Chrome 更新过时的情况，可能会影响更新相关的提示。

2. Chrome 首选项修改
脚本中有几行用于修改 Chrome 的本地配置文件，以改变其在崩溃后的恢复行为：

```bash
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/google-chrome/Default/Preferences
sed -i 's/"exit_type":"Crashed"/"exit_type":"None"/' ~/.config/google-chrome/Default/Preferences
```

这些修改可以防止 Chrome 在非正常退出后显示恢复页面或崩溃警告。

 3. Chrome 策略设置
在脚本的末尾部分，有设置用于管理 Chrome 的企业策略，这些策略可以用来控制 Chrome 的一些行为：

```bash
cat >>/etc/opt/chrome/policies/managed/default_managed_policy.json <<EOL
{"CommandLineFlagSecurityWarningsEnabled": false, "DefaultBrowserSettingEnabled": false}
EOL
```

- `"CommandLineFlagSecurityWarningsEnabled": false` 可能用于禁用因使用命令行标志（如 `--no-sandbox`）而显示的安全警告。
- `"DefaultBrowserSettingEnabled": false` 用来管理默认浏览器设置的提示。

4 结论
你的 Dockerfile 脚本包括了一些策略和修改，旨在减少或消除 Chrome 在特定条件下可能显示的警告和提示。这些设置在自动化测试环境中可能是有用的，但在生产环境中使用时需要谨慎，因为它们可能会掩盖重要的安全问题。始终建议在完全理解每个设置的后果后，谨慎地应用这些配置。如果有更多问题或需要进一步的帮助，请随时提问。

## 重点看第三点
应该通过Chrome 策略设置，CommandLineFlagSecurityWarningsEnabled : false 可能用于禁用因使用命令行标志（如 `--no-sandbox`）而显示的安全警告。

**Comment by luzihang123** [comment]
从 Google Chrome 75 版本开始，`--disable-infobars` 命令行参数已被弃用，这意味着你不能再通过这个参数来关闭 Chrome 的某些信息条，如“Chrome 正在受到自动化软件控制”的提示。然而，你可以使用 Chrome 的企业策略来管理或修改浏览器的行为，包括某些信息的显示。

### 使用企业策略控制 Chrome 行为

虽然没有一个直接替代 `--disable-infobars` 的策略，但你可以利用 Chrome 的企业策略来达到类似的目的，例如通过减少或管理自动化运行时的通知。以下是如何使用企业策略来控制 Chrome 设置的一般方法：

1. **创建或修改策略文件**：
   策略文件通常是 JSON 格式，存放在特定的目录中。对于 Linux 系统，这个位置通常是 `/etc/opt/chrome/policies/managed/` 或 `/etc/chromium/policies/managed/`（如果你使用的是 Chromium）。

2. **示例策略文件**：
   以下是一个示例 JSON 文件，展示了如何设置企业策略来控制 Chrome 的某些功能。虽然没有直接关闭所有信息条的选项，你可以探索如 `"CommandLineFlagSecurityWarningsEnabled"` 这类策略来看是否可以达到你想要的效果。

   ```json
   {
       "CommandLineFlagSecurityWarningsEnabled": false
   }
   ```

   将上述内容保存到一个 JSON 文件中，例如 `my_chrome_policy.json`，并放置在适当的策略文件夹中。

3. **应用策略**：
   确保你的 Chrome 实例能够读取这些策略。如果你是在 Docker 或其他容器化环境中配置这些策略，确保在构建镜像时包含这些策略文件，并且容器具有适当的权限来读取这些文件。

### 注意事项：

- **策略生效**：Chrome 需要重新启动才能使新的策略设置生效。
- **安全考虑**：禁用安全警告会减少浏览器的安全性，应仅在完全了解潜在风险的情况下进行此操作。
- **持续更新**：Google 定期更新 Chrome 和其政策，某些策略可能在新版本中被修改或废弃，定期检查 [Chrome Enterprise Policy List](https://chromeenterprise.google/policies/) 以获取最新信息。

使用企业策略是一种强大的方式来管理 Chrome 的设置和行为，特别是在企业或自动化环境中。如果你有更具体的需求或遇到问题，请提供详细信息，以便进一步帮助你。


具体操作 
dockerfile中添加
```
# 创建策略文件目录
RUN mkdir -p /etc/opt/chrome/policies/managed/

# 添加策略文件
RUN echo '{"CommandLineFlagSecurityWarningsEnabled": false}' > /etc/opt/chrome/policies/managed/default_managed_policy.json
```


搞定：
![image](https://github.com/user-attachments/assets/75b7f437-b522-4e70-b86d-bb7c3cc71b1a)

**Comment by gotoeasy** [comment]
> # 创建策略文件目录
> RUN mkdir -p /etc/opt/chrome/policies/managed/
> 
> # 添加策略文件
> RUN echo '{"CommandLineFlagSecurityWarningsEnabled": false}' > /etc/opt/chrome/policies/managed/default_managed_policy.json
> ```

牛！
