### ISSUE TITLE
安装中文支持以后无法在浏览器中输入中文

### ISSUE THREAD

**Issue by MagicStarTrace** [gotoeasy/docker-ubuntu-desktop#3]
apt-get install fonts-droid-fallback ttf-wqy-zenhei ttf-wqy-microhei fonts-arphic-ukai fonts-arphic-uming

另外远程连接到(ssh)容器也还是无法输入中文，不被识别

**Comment by gotoeasy** [comment]
本镜像目的是VNC远程连接后，像桌面一样直接使用
ssh远程命令极少使用中文，应避免吧，没试过
