### ISSUE TITLE
cannot copy/paste chinese between host and docker

### ISSUE THREAD

**Issue by jingkang99** [gotoeasy/docker-ubuntu-desktop#4]
it is vnc protocol issue. just in case, you know any alternative

![image](https://user-images.githubusercontent.com/10793075/147373412-5fcfeee1-7d69-486e-bb18-2e6dc3132ce8.png)

**Comment by jingkang99** [comment]
by using rdp, paste Chinese is ok

**Comment by gotoeasy** [comment]
或许购买商业版VNC客户端可以解决

**Comment by gotoeasy** [comment]
`1.10.1`版本支持复制中文

**Comment by gotoeasy** [comment]
> `1.10.1`版本支持复制中文

当然，还得是用TigerVNC官方客户端

**Comment by huapox** [comment]
> try this: https://github.com/infrastlabs/docker-headless/blob/dev/_doc/mannual/b1-locale.md
> 
> `docker run -it --rm -e L=zh_CN --net=host infrastlabs/docker-headless`

**Comment by gotoeasy** [comment]
> > try this: https://github.com/infrastlabs/docker-headless/blob/dev/_doc/mannual/b1-locale.md
> > `docker run -it --rm -e L=zh_CN --net=host infrastlabs/docker-headless`
挺好的
