### ISSUE TITLE
安装 chrome 后，打开网站持续崩溃

### ISSUE THREAD

**Issue by echoldman** [gotoeasy/docker-ubuntu-desktop#5]
试过最新版、90.0.4430.72、71.0.3578.80，打开网站三个以上的页面，或者直接打开 YouTube，就会崩溃，关闭 chrome 的硬件加速依然如此。

**Comment by echoldman** [comment]
补充一下，安装最新的 Opera 也是如此。

**Comment by echoldman** [comment]
补充一下，安装了最新版的 Opera 也是如此。

**Comment by gotoeasy** [comment]
机器配置跟上的话应该没事

**Comment by echoldman** [comment]
我是10代i7-10700K，32G内存，3080Ti，需要给docker做特殊配置吗

**Comment by gotoeasy** [comment]
你是怎么装的呢？
我试下来溜得很，我的 i7, 内存20G，打开一堆网页还地图视频，挺好啊
![image](https://user-images.githubusercontent.com/9602197/168589012-2cae4910-bb68-42e0-8166-114493f179ae.png)

**Comment by gotoeasy** [comment]
> 我是10代i7-10700K，32G内存，3080Ti，需要给docker做特殊配置吗

`1.10.1`版本已默认安装谷歌浏览器，随便用。也可以参考检查下你装的差异

**Comment by echoldman** [comment]
赞

> > 我是10代i7-10700K，32G内存，3080Ti，需要给docker做特殊配置吗
> 
> `1.10.1`版本已默认安装谷歌浏览器，随便用。也可以参考检查下你装的差异
