### ISSUE TITLE
关于VNC连接超时黑屏问题

### ISSUE THREAD

**Issue by basipotato** [gotoeasy/docker-ubuntu-desktop#6]
您好，非常感谢您提供的容器化VNC远程桌面方案，我现在遇到了点小问题，VNC客户端连接后长时间不做操作，下次再次连接会黑屏，不知道是超时导致还是屏幕锁定了，SSH是可以正常连接的，您知道可能因为什么原因导致的吗

**Comment by gotoeasy** [comment]
这个有点爱莫能助的样子了。
我用官方的`TigerVNC`客户端，试下连接半个月未操作的服务，结果正常。

**Comment by basipotato** [comment]
我去掉了这个选项，貌似是好了，不知道是不是这个原因导致的
![image](https://user-images.githubusercontent.com/44697689/179721972-429b6a5f-77e7-4c1f-aa2a-0530536d951a.png)
