### ISSUE TITLE
浏览器访问支持

### ISSUE THREAD

**Issue by mysoft999** [gotoeasy/docker-ubuntu-desktop#9]
大佬好，请问可以支持浏览器访问计划吗？谢谢

**Comment by gotoeasy** [comment]
用 novnc 服务的话是可以浏览器访问打开系统界面，不过尝试后性能较差不满意，除非哪天性能确实有所改善，不然暂时不会支持。

如果只是想用浏览器打开命令行窗口，那webssh就可以，也非常方便，但和本仓库目的不同，所以也没直接支持

**Comment by mysoft999** [comment]
大佬，Guacamole这个看样挺好的？可以浏览器访问linux桌面

**Comment by gotoeasy** [comment]
> 大佬，Guacamole这个看样挺好的？可以浏览器访问linux桌面

浏览器不是不可以访问操作linux桌面，而是操作性能不如意体验不佳
Guacamole可以先留意下，有空时试试

**Comment by mysoft999** [comment]
> > 大佬，Guacamole这个看样挺好的？可以浏览器访问linux桌面
> 
> 浏览器不是不可以访问操作linux桌面，而是操作性能不如意体验不佳 Guacamole可以先留意下，有空时试试

大佬，我加您Q没通过

**Comment by gotoeasy** [comment]
> 大佬，我加您Q没通过

基本上不用Q
